name: Composer require checker

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - '.github/workflows/composer-require-checker.yml'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer-require-checker:
    uses: yiisoft/actions/.github/workflows/composer-require-checker.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0', '8.1', '8.2', '8.3', '8.4']
